spring:
  application:
    name: g_67_shop # Имя приложения (для логов и сервисов)
  datasource: # настройки подключения к базе данных
    driver-class-name: org.postgresql.Driver # Используем драйвер PostgreSQL
    # Формат: [протокол]:[тип_бд]://[хост]:[порт]/[имя_базы]
    url: jdbc:postgresql://localhost:5432/g_67_shop
    #      |      |          |        |       |
    #      |      |          |        |       └── Название базы данных
    #      |      |          |        └──────── Порт (у Postgres по умолчанию 5432)
    #      |      |          └───────────────── Адрес сервера (localhost — твой ПК)
    #      |      └──────────────────────────── Тип СУБД (PostgreSQL)
    #      └─────────────────────────────────── Технология соединения в Java (JDBC)
    username: postgres # Логин пользователя БД
    password: qwerty007 # Пароль пользователя БД
  liquibase: # Автоматическое создание таблиц
    # Путь к главному файлу, в котором описаны изменения структуры БД
    # classpath: — смотрим в папку src/main/resources
    # /db/changelog/ — идем по этим папкам
    # db.changelog-master.xml — главный файл, который управляет всеми остальными
    change-log: classpath:/db/changelog/db.changelog-master.xml
#  Вот этот файлик application.yaml является главным конфигурационным файлом нашего приложения.
#  Здесь мы прописываем в том числе подключение для базы данных.

#  Если бы мы с вами выбрали другой формат настроек, то это бы прописывалось вот таким вот образом.
#  Вот если бы мы с вами выбрали формат файла настроек properties, то настройки бы выглядели вот так.
#  Каждая настройка прописывалась бы полным путем. spring.application.name=g_67_shop
server:
  port: 8081
